import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import AppProvider from '@/components/app-provider'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
}

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en' suppressHydrationWarning>
         <body className={`antialiased`}>
            <AppProvider>
               <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
                  <main className='container text-sm'>{children}</main>
               </ThemeProvider>
            </AppProvider>
         </body>
      </html>
   )
}
